- policy/modules/services/xserver.fc
On Debian, /usr/bin/Xorg is only a shell script which executes
/usr/lib/xorg/Xorg.wrap, which is a SUID binary wrapper around
/usr/lib/xorg/Xorg.
> Label Xorg server binary correctly on Debian

- policy/modules/system/init.te
At early boot, I get the following messages in dmesg:
audit: type=1400 audit(1452851002.184:3): avc:  denied  { audit_read } for  pid=1 comm="systemd" capability=37 scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=capability2 permissive=1
systemd[1]: Listening on Journal Audit Socket.
> Allow systemd the audit_read capability

- man/man8/git_selinux.8
- man/man8/httpd_selinux.8
- policy/modules/admin/bootloader.if
- policy/modules/kernel/corecommands.if
- policy/modules/kernel/corenetwork.if.in
- policy/modules/kernel/corenetwork.if.m4
- policy/modules/kernel/devices.if
- policy/modules/kernel/domain.if
- policy/modules/kernel/files.if
- policy/modules/kernel/filesystem.if
- policy/modules/kernel/kernel.if
- policy/modules/kernel/storage.if
- policy/modules/system/init.if
- policy/modules/system/iptables.if
- policy/modules/system/locallogin.if
- policy/modules/system/miscfiles.if
- policy/modules/system/modutils.if
- policy/modules/system/selinuxutil.if
- policy/modules/system/userdomain.if
Hello,
Here are some commits which fix some typographical errors I found in refpolicy, either by encountering them in manual file inspection (like the typo in init_dbus_chat interface and the ones in the corenetwork module), by grabbing them from other issues (I posted a comment in PR https://github.com/TresysTechnology/refpolicy/pull/7 almost one year ago which got no reply) and by using a dirty script which finds interfaces sharing the same comment (in order to find copy-and-paste errors). Could you please merge them?
Cheers!
> Several typo fixes

- policy/modules/system/iptables.te
Since version 0.4.0, firewalld uses *tables-restore to speedup the
load of the rules
> Allow {eb,ip,ip6}tables-restore to read files in /run/firewalld

- Makefile
- config/appconfig-mcs/lxc_contexts
- config/appconfig-mls/lxc_contexts
- config/appconfig-standard/lxc_contexts
selinux_lxc_contexts_path() function in upstream libselinux points to
this config file. It is ATM used by libvirt.
The file from Fedora also contains sandbox_lxc_process and
sandbox_kvm_process parameters, but I cannot find where they are used,
keep them out of the file for the time being.
> Add lxc_contexts config file

- policy/modules/kernel/kernel.te
When a device gets removed, for example with ``cryptsetup close``,
kdevtmpfs (a kernel thread) removes its entry from devtmpfs filesystem:
avc:  denied  { unlink } for  pid=48 comm="kdevtmpfs"
name="dm-4" dev="devtmpfs" ino=144111
scontext=system_u:system_r:kernel_t
tcontext=system_u:object_r:fixed_disk_device_t tclass=blk_file
Allow this access on systems using systemd.
> Allow kdevtmpfs to unlink fixed disk devices

- policy/mls
- policy/modules/kernel/mls.if
- policy/modules/kernel/mls.te
- policy/modules/system/logging.te
Hi Tresys!
When building MLS policy, /dev/log socket gets created with just mls_systemhigh sensitivity (s3 in my case, build.conf in [0]), and that contradict mls constraints [1].
I don't quite like setting all of syslogd_t to mlstrustedobject, so the proposed patch does what was discussed in [this thread from 2010](http://oss.tresys.com/pipermail/refpolicy/2010-November/003444.html).
Is this the right direction, or i'm missing something obvious here and should fix that elsewhere?
I didn't touch the "mlsconstrain unix_stream_socket connectto" one, since i haven't seen it in logs yet.
[0] build.conf for reference
```shell
TYPE = mls
NAME = custom
DISTRO = debian
UNK_PERMS = reject
DIRECT_INITRC = n
MONOLITHIC = n
UBAC = y
CUSTOM_BUILDOPT =
MLS_SENS = 4
MLS_CATS = 32
MCS_CATS = 32
QUIET = n …
```
> Adds attribute mlstrustedsocket, along with the interface.

- .travis.yml
Hello,
When testing Travis-CI environments other than the traditional Ubuntu 12.04 VM, I needed to drop sudo from the Travis build script (its use is forbidden in containters). This led me to install the toolchain in $HOME. As this is also useful to work around issues that @perfinion  found in the Ubuntu 14.04 Beta VMs (about conflicting toolchains), I am upstreaming my work in this pull request.
When doing my tests I did not find any significant performance difference between the environment so I did not modify the one which is currently used. Nevertheless with my changes it is now possible to change to an other Travis-CI environment with only slight modifications to ``.travis.yml``.
Cheers
> Make Travis-CI build without using sudo

- .gitignore
- Vagrantfile
Run `vagrant up` to get a fully-loaded Fedora 24 cloud VM running with everything you need installed for basic SELinux testing and development.
> Add Vagrant box for development.

- Makefile
Since the awk scripts appear to use some GNU extensions, make sure we always use $(AWK).
Fixes an issue where the system /usr/bin/awk may be another implementation, say mawk on a Ubuntu system.
> Use $(AWK) not plain awk

- support/fc_sort.c
Value stored to 'i' is never read.
Variable 'j' is never used.
> fc_sort: cleanup warnings caught by clang tidy / static analyzer.

- policy/modules/system/sysnetwork.te
```
#============= dhcpc_t ==============
allow dhcpc_t avahi_exec_t:file execute_no_trans;
#!!!! This avc is allowed in the current policy
allow dhcpc_t avahi_exec_t:file { read execute open };
```
> allow dhcp_t to domtrans into avahi

- policy/modules/kernel/terminal.fc
* label content of /dev/pts/ correctly
> terminal: label content of /dev/pts/ correctly

- policy/modules/kernel/filesystem.if
- policy/modules/system/selinuxutil.te
userdomain should not edit labels of kernel pseudo filesystems, but allow setfiles/restorecon(d) to check the contexts for correctness
> setfiles: allow getattr to kernel pseudo fs

- policy/modules/kernel/files.fc
encourage private types for /run and /var/lock by not providing default contexts anymore
> changes to /run, /run/user and /var/lock

- policy/modules/system/selinuxutil.fc
- policy/modules/system/selinuxutil.te
* no negative permission matching for newrole_t:process
* do not label /usr/lib/selinux as policy_src_t, otherwise semodule can not run /usr/lib/selinux/hll/pp
* reorder label for /run/restorecond.pid
* fix systemd related denials
> update selinuxutil module

- policy/modules/system/locallogin.te
* do not grant permissions by negativ matching
* separate dbus from consolekit block for systemd
> update locallogin module

- policy/modules/system/userdomain.if
prohibit open by using inherited perms, introduced by Russell Coker
> userdomain: strengthen user terminals access

- Rules.modular
- policy/modules/kernel/devices.fc
Hello,
This Pull Request makes ``make validate`` able to detect some errors related to file contexts, using ``setfiles``. I  have written it after I stumbled on git mismerges in ``systemd.fc`` which were not reported by ``make validate`` but made loading the policy fail.
When I tested this change on Travis-CI, the builds with ``DISTRO=debian MONOLITHIC=n`` failed because of a syntax issue cause by a single quote in a comment. Even though I find it weird that m4 keeps the comments (contrary to the C preprocessor for example), I fixed this failure by removing the buggy quote.
> Make "validate" target verify file contexts

- policy/modules/system/getty.fc
- policy/modules/system/getty.if
- policy/modules/system/getty.te
* reorder file contexts
* (a)getty is a long running domain on debian -> init_daemon_domain
* rename getty_var_run_t into getty_runtime_t
* remove unneeded and confusing init permissions
* delete access on generic pids
* remove invalid etc filetrans: getty has no create permissions for its config files
> overlook getty module

- support/pyplate.py
- support/segenxml.py
Python 3.6 complains about the strings which are used as regular
expression in the support scripts:
File "support/segenxml.py", line 37
INTERFACE = re.compile("^\s*(interface|template)\(`(\w*)'")
^
SyntaxError: invalid escape sequence \s
> Use raw strings in regular expressions

- support/fc_sort.c
Using the LLVM static analyzer, we get a warning about leaked memory
pointed by bcurrent. Since the warning happens within "main", we
don't care about deallocating the memory and just call "exit" which
gets rid of the warning.
> Avoid memory leak warning.

- support/genhomedircon.py
python3.6 will error out with the message "invalid escape sequence (\"
in genhomedircon.py when re.sub is called.
Turn the string into a raw string to fix the issue.
> fix regex escape sequence error.

- policy/modules/system/ipsec.te
The strongSwan starter application, running as ipsec_supervisor_t, uses signull to check for the existence of other ipsec_t and ipsec_supervisor_t running processes. Without the signull permission running 'ipsec start' multiple times will cause multiple instances of the charon daemon to run.
> system/ipsec: Add signull access for strongSwan

- support/fc_sort.c
Rather than using malloc to allocated nodes and setting all the fields,
just use calloc.
Signed-off-by: William Roberts <william.c.roberts@intel.com>
> fc_sort: use calloc instead of malloc

- policy/modules/system/iptables.te
iptables/xtables-multi for some reasons need the getattr permission on /proc.
```
type=PROCTITLE msg=audit(01/03/18 04:41:03.464:5338) : proctitle=iptables -w -n -L INPUT 
type=SYSCALL msg=audit(01/03/18 04:41:03.464:5338) : arch=x86_64 syscall=statfs success=yes exit=0 a0=0x7f0acb8460b6 a1=0x7ffe218abd10 a2=0x7ffe218abd90 a3=0x0 items=0 ppid=4059 pid=4060 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=(none) ses=unset comm=iptables exe=/sbin/xtables-multi subj=system_u:system_r:iptables_t:s0 key=(null) 
type=AVC msg=audit(01/03/18 04:41:03.464:5338) : avc:  denied  { getattr } for  pid=4060 comm=iptables name=/ dev="proc" ino=1 scontext=system_u:system_r:iptables_t:s0 tcontext=system_u:object_r:proc_t:s0 tclass=filesystem permissive=1
``` …
> xtables-multi wants to getattr of the proc fs
